# Generated by Django 5.2.15 on 2026-08-06 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expression', '0001_initial'),
        ('physio', '0001_initial'),
        ('speech', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expression.expressionrecord')),
                ('physio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='physio.physiorecord')),
                ('speech_emotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speech.speechemotionrecord')),
                ('transcript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='speech.transcriptrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
