# Generated by Django 5.2.15 on 2026-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('angry', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('fear', models.FloatField(default=0.0)),
                ('happy', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('sad', models.FloatField(default=0.0)),
                ('surprise', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('face_image_path', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IdentityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('person_name', models.CharField(default='unknown', max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_unknown', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RegisteredFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=128, unique=True)),
                ('embedding', models.BinaryField()),
                ('thumbnail_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
