# Generated by Django 5.2.15 on 2026-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='ollama', max_length=16)),
                ('ollama_model', models.CharField(default='qwen2.5', max_length=128)),
                ('deepseek_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='registeredface',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='registeredface',
            name='major',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='registeredface',
            name='student_no',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
