# Generated by Django 5.2.15 on 2026-08-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expression', '0002_llmconfig_registeredface_gender_registeredface_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='ollama_model',
            field=models.CharField(default='qwen2.5:7b', max_length=128),
        ),
    ]
