# Generated by Django 5.2.15 on 2026-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechEmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('emotion_label', models.CharField(max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('pitch_mean', models.FloatField(blank=True, null=True)),
                ('rms_mean', models.FloatField(blank=True, null=True)),
                ('speaking_rate', models.FloatField(blank=True, null=True)),
                ('audio_path', models.CharField(blank=True, default='', max_length=512)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField(default='')),
                ('sentiment_label', models.CharField(default='', max_length=32)),
                ('sentiment_confidence', models.FloatField(default=0.0)),
                ('keywords', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
