# Generated by Django 5.2.15 on 2026-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('hr_avg', models.FloatField(default=0.0)),
                ('hr_min', models.FloatField(default=0.0)),
                ('hr_max', models.FloatField(default=0.0)),
                ('temp_avg', models.FloatField(default=0.0)),
                ('skin_humidity_avg', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
