# Generated by Django 5.2.15 on 2026-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('port', models.CharField(default='a', max_length=1)),
                ('temp', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('pulse', models.FloatField(default=0.0)),
                ('gsr', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SerialConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('port_a', models.CharField(default='COM6', max_length=64)),
                ('port_b', models.CharField(default='COM5', max_length=64)),
                ('baudrate', models.IntegerField(default=115200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='physiorecord',
            name='gsr_avg',
            field=models.FloatField(default=0.0),
        ),
    ]
